/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>
#include <GPIOStructs.h>

int main(void)
{
	RCC_AHB1ENR_t volatile *const bPort = (RCC_AHB1ENR_t*) 0x40023830;
	GPIOx_MODER_t volatile *const bMode = (GPIOx_MODER_t*) 0x40020400;


}
